DjangoApollon/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path
from django.views import static

from app.views import *
from app.views.playlist import PlaylistList, PlaylistDetail, PlaylistCreate, PlaylistDelete, PlaylistUpdate, \
    follow_playlist, unfollow_playlist, delete_song_from_playlist
from app.views.profile import ProfileUpdate, PublicProfile
from app.views.song import SongDetail, create_if_not_exists, add_song_to_playlist

urlpatterns = [
    # Favicon
    url(r'^favicon.ico/$', lambda x: HttpResponseRedirect(settings.STATIC_URL + 'favicon.ico')),

    # Page d'accueil
    url('^$', SplashView.as_view(), name='app_home'),
    # Admin
    path('admin/', admin.site.urls),
    # Authentification
    url(r'^sign_in/?$', UserLoginView.as_view(), name='app_login'),
    url(r'^sign_out/?$', UserLogoutView.as_view(), name='app_logout'),
    url(r'^sign_up/?$', RegisterView.as_view(), name='app_register'),
    path('reset_password/', CustomPasswordResetView.as_view(), name='app_reset_password'),
    path('reset_password/sent', PasswordResetWasSentView.as_view(), name='app_reset_password_mail_sent'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', CustomPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset_password/complete', PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('sign_up/thanks', ThanksForSigningUpView.as_view(), name='app_thanks_for_signing_up'),
    path('sign_up/account_confirmation', AccountConfirmationView.as_view(), name='app_account_confirmation'),
    # Moteur de recherche
    path('search_engine/<str:search>', searchSongs, name='search_songs'),
    path('search_engine/song/<int:search>', getSong, name='get_song'),
    path('search_engine/artist/<int:search>', getSong, name='get_artist'),
    # Changement de langue
    path('change_lang/<str:lang_code>', change_language, name='app_change_language'),

    # Gestion du profil
    path('me/update/<int:pk>', ProfileUpdate.as_view(), name='app_profile_update'),
    # Profils publics
    url(r'^profiles/(?P<slug>[\w.@+-]+)$', PublicProfile.as_view(), name='app_public_profile'),

    # Core Apollon
    # Gestion des playlists (création, liste personnelle, etc.)
    path('me/playlists/new', PlaylistCreate.as_view(), name='app_new_playlist'),
    path('me/playlists', PlaylistList.as_view(), name='app_user_playlists'),
    path('me/playlists/delete/<int:pk>', PlaylistDelete.as_view(), name='app_playlist_delete'),
    path('me/playlists/update/<int:pk>', PlaylistUpdate.as_view(), name='app_playlist_update'),
    path('playlists/<str:username>/<slug:pk>', PlaylistDetail.as_view(), name='app_playlist_detail'),
    path('playlists/follow', follow_playlist, name='follow_playlist'),
    path('playlists/unfollow', unfollow_playlist, name='unfollow_playlist'),
    path('playlists/delete-song-from-playlist', delete_song_from_playlist, name='delete_song_from_playlist'),

    # Gestion des chansons (détail, recherche et ajout à une playlist existante).
    path('me/add-song-to-playlist/', add_song_to_playlist, name='app_add_song_to_playlist'),
    path('song/<slug:slug>', SongDetail.as_view(), name="app_song_detail"),
    path('song/create_if_not_exists/<int:genius_id>', create_if_not_exists, name="app_create_song_if_not_exists"),

    # Vue des moteurs de recherche
    path('search/playlists', PlaylistSearchEngine.as_view(), name='app_search_playlists'),
    path('search/songs', SongSearchEngine.as_view(), name='app_search_songs'),
]

urlpatterns += i18n_patterns(
    # Page d'accueil
    url('^$', SplashView.as_view(), name='app_home'),
    url(r'^sign_in/?$', UserLoginView.as_view(), name='app_login'),
    url(r'^sign_out/?$', UserLogoutView.as_view(), name='app_logout'),
    url(r'^sign_up/?$', RegisterView.as_view(), name='app_register'),
    path('reset_password/', CustomPasswordResetView.as_view(), name='app_reset_password'),
    path('reset_password/sent', PasswordResetWasSentView.as_view(), name='app_reset_password_mail_sent'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', CustomPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset_password/complete', PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('sign_up/thanks', ThanksForSigningUpView.as_view(), name='app_thanks_for_signing_up'),
    path('sign_up/account_confirmation', AccountConfirmationView.as_view(), name='app_account_confirmation'),

    # Gestion du profil
    path('me/update/<int:pk>', ProfileUpdate.as_view(), name='app_profile_update'),
    # Profils publics
    url(r'^profiles/(?P<slug>[\w.@+-]+)$', PublicProfile.as_view(), name='app_public_profile'),

    # Core Apollon
    # Gestion des playlists (création, liste personnelle, etc.)
    path('me/playlists/new', PlaylistCreate.as_view(), name='app_new_playlist'),
    path('me/playlists', PlaylistList.as_view(), name='app_user_playlists'),
    path('me/playlists/delete/<int:pk>', PlaylistDelete.as_view(), name='app_playlist_delete'),
    path('me/playlists/update/<int:pk>', PlaylistUpdate.as_view(), name='app_playlist_update'),
    path('playlists/<str:username>/<slug:pk>', PlaylistDetail.as_view(), name='app_playlist_detail'),
    # Gestion des chansons (détail, recherche et ajout à une playlist existante).
    path('song/<slug:slug>', SongDetail.as_view(), name="app_song_detail"),
    # Vue des moteurs de recherche
    path('search/playlists', PlaylistSearchEngine.as_view(), name='app_search_playlists'),
    path('search/songs', SongSearchEngine.as_view(), name='app_search_songs'),
)

app/forms/profile.py
from django import forms
from django.contrib.auth.models import User
from django.forms import widgets, ModelForm
from django.utils.translation import gettext_lazy as _


class ProfileForm(ModelForm):
    first_name = forms.CharField(max_length=250,
                                 label=_('First name'),
                                 widget=widgets.Input(
                                     attrs={
                                         'class': 'uk-input',
                                         'placeholder': _('First name')
                                     }
                                 ))
    last_name = forms.CharField(max_length=250,
                                label=_('Last name'),
                                widget=widgets.Input(
                                    attrs={
                                        'class': 'uk-input',
                                        'placeholder': _('Last name')
                                    }
                                ))

    biography = forms.CharField()

    class Meta:
        model = User
        fields = ('first_name', 'last_name')

app/views/profile.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import UpdateView, DetailView
from django.utils.translation import gettext_lazy as _

from app.forms.profile import ProfileForm
from app.models import UserProfile, Playlist


class ProfileUpdate(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = User
    template_name = 'profile/update.html'
    form_class = ProfileForm
    success_message = _('Your profile was successfully updated')

    def test_func(self):
        return self.get_object() == self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        currentProfile = UserProfile.objects.get(user=self.request.user)
        context['profile'] = currentProfile
        return context

    def form_valid(self, form):
        if form.is_valid():
            profile = UserProfile.objects.get(user=self.request.user)
            profile.biography = form.cleaned_data['biography']
            profile.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('app_profile_update', kwargs={'pk': self.request.user.id})


class PublicProfile(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'profile/public-profile.html'
    slug_field = 'username'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # On doit l'écraser parce que sur les User Detail Views de User model, l'indice de contexte
        # 'user' avec celui qu'on observe...
        context['user'] = self.request.user
        context['profile'] = UserProfile.objects.get(user=self.object)
        context['playlists_created'] = Playlist.objects.filter(created_by=context['profile'], is_public=True)
        context['total_songs'] = sum([playlist.songs.count() for playlist in context['playlists_created']])
        context['total_follower'] = sum([playlist.followers.count() for playlist in context['playlists_created']])
        return context

templates/profile/public-profile.html
{% extends 'layouts/home.html' %}
{% load static i18n custom_tags%}
{% block content %}
    <div class="uk-padding uk-grid-collapse" uk-grid>
        <div class="uk-width-1-1">
            <h1 class="uk-heading-large uk-inline">
                {{object.username}}
                <!-- LAST LOGIN -->
                <span class="uk-text-meta uk-text-nowrap">
                {% trans 'Last connection : ' %}<strong>{{ object.last_login }}</strong>
                <span class="uk-badge" style="background-color: #32d296"></span>
            </span>
            </h1>
        </div>
        <div class="uk-width-1-1 uk-margin-bottom">

        </div>
        <div class="uk-width-2-3@s">
            <!-- BIOGRAPHY -->
            <blockquote class="">
                <p class="uk-margin-small-bottom">{{ profile.biography }}</p>
                <footer>{% trans 'An awesome user of ' %} <cite class="uk-text-primary">Apollon</cite></footer>
            </blockquote>

            <!-- STATS -->
            <div class="uk-grid-collapse uk-child-width-1-2@m" uk-grid>
                <!-- JOINED DATE -->
                <div class="uk-card uk-card-secondary uk-card-body">
                    <h3 class="uk-card-title uk-text-success uk-text-center"><span uk-icon="icon:info;ratio:2"></span></h3>
                    <p class="uk-text-center">
                        {% if object.first_name and object.last_name %}
                            {{ object.first_name }} {{ object.last_name }} {% trans 'joined us on' %}
                            <span class="uk-text-success">{{ object.date_joined }}</span>
                        {% else %}
                            {{ object.username }} {% trans 'joined us on' %}
                            <span class="uk-text-success">{{ object.date_joined }}</span>
                        {% endif %}
                    </p>
                </div>
                <!-- VERIFIED ACCOUNT -->
                <div class="uk-card uk-card-secondary uk-card-body">
                    {% if profile.is_valid %}
                        <h3 class="uk-card-title uk-text-success uk-text-center"><span uk-icon="icon:check;ratio:2"></span></h3>
                        <p class="uk-text-center">
                            {% trans 'This user has a <span class="uk-text-success">verified</span> account' %}
                        </p>
                    {% else %}
                        <h3 class="uk-card-title uk-text-warning uk-text-center"><span uk-icon="icon:ban;ratio:2"></span></h3>
                        <p class="uk-text-center">
                            {% trans 'This user has <span class="uk-text-warning">not verified</span> his account.' %}
                        </p>
                    {% endif %}
                </div>

                <div class="uk-width-1-1">
                    <ul class="uk-margin-top uk-list uk-list-divider uk-list-large">
                        <li>
                            <h1 class="uk-text-lighter">
                                <span>{{ playlists_created|length }}</span> {% trans 'Playlists' %}
                            </h1>
                        </li>
                        <li>
                            <h1 class="uk-text-lighter">
                                <span>{{ total_follower }}</span> {% trans 'Followers' %}
                            </h1>
                        </li>
                        <li>
                            <h1 class="uk-text-lighter">
                                <span>{{ total_songs }}</span> {% trans 'Songs' %}
                            </h1>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <div class="uk-width-1-3@s">
            <p><span class="uk-margin-right uk-text-primary" uk-icon="question"></span>{% trans 'Click on the "+" to see the playlists.' %}</p>
            <div class="uk-flex uk-flex-center">
                <div class="uk-inline uk-light">
                    <img class="uk-border-rounded" height="" width="350" src="{% static 'img/vinyls-collection.jpg' %}" alt="" uk-img>
                    {% for playlist in playlists_created %}
                        <a class="uk-position-absolute uk-transform-center"
                           href="#playlist-{{ playlist.id }}"
                           style="left: {% random_int 0 100 %}%; top: {% random_int 0 100 %}%"
                           uk-toggle uk-marker></a>
                        <div id="playlist-{{ playlist.id }}" uk-modal>
                            <div class="uk-modal-dialog uk-modal-body">
                                <h2 class="uk-modal-title">{{ playlist.title }}</h2>
                                <p class="uk-text-meta">{{ playlist.description }}</p>
                                <span class="uk-text-meta">
                                    <span class="uk-text-primary">{{ playlist.songs|length }}</span> {% trans 'Songs' %}
                                </span>
                                <div class="uk-flex-center uk-flex">
                                    <a class="uk-button uk-button-default" href="{% url 'app_playlist_detail' username=object.username pk=playlist.id%}">
                                        {% trans 'See' %}
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/profile/update.html
{% extends 'layouts/home.html' %}
{% load static i18n custom_tags%}
{% block content %}
    <div class="uk-padding-large">
        <h1>{% trans 'My profile' %}</h1>
        <p class="uk-text-meta">
            {% trans 'Update your profile meta content' %}
        </p>

        {% if not profile.is_valid %}
            <div class="uk-alert-danger" uk-alert>
                <a class="uk-alert-close uk-margin-right" uk-close></a>
                <p>{% trans 'Your account was still not validated content' %}</p>
            </div>
        {% endif %}

        <form class="" action="" id="{{ form.auto_id }}" method="post">
            {% csrf_token %}

            <span>{% trans 'First name' %}</span>
            <div class="uk-inline uk-width-1-1 uk-margin-bottom">
                <a class="uk-form-icon" uk-icon="icon: info"></a>
                {{ form.first_name }}
            </div>

            <span>{% trans 'Last name' %}</span>
            <div class="uk-inline uk-width-1-1 uk-margin-bottom">
                <a class="uk-form-icon" uk-icon="icon: info"></a>
                {{ form.last_name }}
            </div>

            <span>{% trans 'Biography' %}</span>
            <div class="uk-inline uk-width-1-1 uk-margin-bottom">
                <a class="uk-form-icon" uk-icon="icon: quote-right"></a>
                <textarea name="biography" cols="40" rows="10" class="uk-input"
                          placeholder="{% trans 'Biography' %}" maxlength="1000"
                          id="id_biography">{{ profile.biography }}</textarea>
            </div>

            <div class="uk-margin-top uk-flex uk-flex-center">
                <button type="submit" class="uk-margin-right uk-button uk-button-large uk-button-primary uk-button-default">{% trans 'Update' %}</button>
                <a href="{% url 'app_public_profile' object.username %}" class="uk-margin-left uk-button uk-button-large uk-button-default uk-button-default">{% trans 'See public profile' %}</a>
            </div>
        </form>
    </div>

    <script>
        $(document).ready(function () {
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        UIkit.notification('{{ field.label }} : {{ error }}', 'danger');
                    {% endfor %}
                {% endfor %}
            {% endif %}
        })
    </script>
{% endblock %}